version: '3.8'

services:
  # PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
      - redis
    ports:
      - 9000:9000

  # MySQL service
  db:
    image: mysql:5.7
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  # Redis service
  redis:
    image: redis:alpine
    container_name: laravel-redis
    networks:
      - laravel_network

  # MailHog service (for local email development)
  smtp:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "1025:1025"  # SMTP Port
      - "8025:8025"  # Web interface to view mails
    networks:
      - laravel_network

  # Nginx service (optional, if you want a reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel_network

# Volumes
volumes:
  db_data:
    driver: local

# Networks
networks:
  laravel_network:
    driver: bridge
